manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: klausweiss
      url-base: https://github.com/klausweiss
  projects:
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk
      remote: klausweiss
      revision: fix/adaptive-keys
  self:
    path: config
