manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: krikun98
      url-base: https://github.com/krikun98/zmk.git  
    - name: zmk
      remote: krikun98
      revision: mousepr
      import: app/west.yml
  self:
    path: config
