manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ascaletty
      url-base: https://github.com/ascaletty
  projects:
    - name: zmk
      remote: ascaletty
      revision: mouse
      import: app/west.yml
  self:
    path: config
